=== GitEntity/web-programming/qualifications.dtd
<!ELEMENT qualifications (qualification+, higher-qualification?, institution+)>
<!ELEMENT qualification (year, (certificate | diploma | degree))>
<!ELEMENT higher-qualification EMPTY>
<!ELEMENT year (#PCDATA)>
<!ELEMENT certificate (#PCDATA)>
<!ELEMENT diploma (#PCDATA)>
<!ELEMENT degree (#PCDATA)>
<!ELEMENT institution (name)>
<!ELEMENT name (#PCDATA)>

=== GitEntity/web-programming/ex3.xml
<?xml version='1.0'?>
<!DOCTYPE qualifications SYSTEM "qualifications.dtd">
<qualifications>
	<qualification>
		<year>2001</year>
		<diploma>Electronic Engineering</diploma>
	</qualification>
	<qualification>
		<year>2005</year>
		<degree>Computer Science</degree>
	</qualification>
	<higher-qualification/>
	<institution>
		<name>Oxford University</name>
	</institution>
	<institution>
		<name>MIT</name>
	</institution>
</qualifications>
